<?php

use Illuminate\Database\Seeder;

class katalogs extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('katalogs')->get()->count() == 0){

            DB::table('katalogs')->insert([

                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 1,
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'images/katalogs/Vaks1.jpg',
                    'lpp_en' => 'images/katalogs/Vaks1.jpg',
                    'lpp_ru' => 'images/katalogs/Vaks1.jpg',
                    'btnlabel_lv' => '',
                    'btnlabel_en' => '',
                    'btnlabel_ru' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 2,
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'images/katalogs/lpp1.jpg',
                    'lpp_en' => 'images/katalogs/lpp1.jpg',
                    'lpp_ru' => 'images/katalogs/lpp1.jpg',
                    'btnlabel_lv' => '',
                    'btnlabel_en' => '',
                    'btnlabel_ru' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 3,
                    'btn_links' => '',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '80',
                    'btn_left' => '57',
                    'lpp_lv' => 'images/katalogs/lpp2.jpg',
                    'lpp_en' => 'images/katalogs/lpp2.jpg',
                    'lpp_ru' => 'images/katalogs/lpp2.jpg',
                    'btnlabel_lv' => 'Apskatīt',
                    'btnlabel_en' => 'Posmotret',
                    'btnlabel_ru' => 'Visit',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 4,
                    'btn_links' => '',
                    'btn_krasa' => 'btn-base-2',
                    'btn_top' => '91',
                    'btn_left' => '30',
                    'lpp_lv' => 'images/katalogs/lpp3.jpg',
                    'lpp_en' => 'images/katalogs/lpp3.jpg',
                    'lpp_ru' => 'images/katalogs/lpp3.jpg',
                    'btnlabel_lv' => 'Galerija',
                    'btnlabel_en' => 'Gallery',
                    'btnlabel_ru' => 'Gaļereja',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 5,
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'images/katalogs/lpp4.jpg',
                    'lpp_en' => 'images/katalogs/lpp4.jpg',
                    'lpp_ru' => 'images/katalogs/lpp4.jpg',
                    'btnlabel_lv' => 'Galerija',
                    'btnlabel_en' => 'Gallery',
                    'btnlabel_ru' => 'Gaļereja',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 6,
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'images/katalogs/lpp5.jpg',
                    'lpp_en' => 'images/katalogs/lpp5.jpg',
                    'lpp_ru' => 'images/katalogs/lpp5.jpg',
                    'btnlabel_lv' => '',
                    'btnlabel_en' => '',
                    'btnlabel_ru' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 7,
                    'btn_links' => '',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '80',
                    'btn_left' => '57',
                    'lpp_lv' => 'images/katalogs/lpp6.jpg',
                    'lpp_en' => 'images/katalogs/lpp6.jpg',
                    'lpp_ru' => 'images/katalogs/lpp6.jpg',
                    'btnlabel_lv' => 'Skatīt galeriju',
                    'btnlabel_en' => 'Check',
                    'btnlabel_ru' => 'Posmotrt Gaļereju',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 8,
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'images/katalogs/lpp7.jpg',
                    'lpp_en' => 'images/katalogs/lpp7.jpg',
                    'lpp_ru' => 'images/katalogs/lpp7.jpg',
                    'btnlabel_lv' => '',
                    'btnlabel_en' => '',
                    'btnlabel_ru' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 9,
                    'btn_links' => '',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '80',
                    'btn_left' => '57',
                    'lpp_lv' => 'images/katalogs/lpp8.jpg',
                    'lpp_en' => 'images/katalogs/lpp8.jpg',
                    'lpp_ru' => 'images/katalogs/lpp8.jpg',
                    'btnlabel_lv' => 'Apskatīt',
                    'btnlabel_en' => 'Click',
                    'btnlabel_ru' => 'Smotri',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 10,
                    'btn_links' => 'https://youtu.be/MbQ8wjkkzPw',
                    'btn_krasa' => 'btn-b-base-2',
                    'btn_top' => '90',
                    'btn_left' => '50',
                    'lpp_lv' => 'images/katalogs/lpp9.jpg',
                    'lpp_en' => 'images/katalogs/lpp9.jpg',
                    'lpp_ru' => 'images/katalogs/lpp9.jpg',
                    'btnlabel_lv' => 'Apskatīt video',
                    'btnlabel_en' => 'Video',
                    'btnlabel_ru' => 'Video',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 11,
                    'btn_links' => '',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '90',
                    'btn_left' => '25',
                    'lpp_lv' => 'images/katalogs/lpp10.jpg',
                    'lpp_en' => 'images/katalogs/lpp10.jpg',
                    'lpp_ru' => 'images/katalogs/lpp10.jpg',
                    'btnlabel_lv' => 'Apskatīt',
                    'btnlabel_en' => 'Click',
                    'btnlabel_ru' => 'Smotreķ',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'vietaLimeni' => 12,
                    'btn_links' => '',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '70',
                    'btn_left' => '32',
                    'lpp_lv' => 'images/katalogs/Vaks2.jpg',
                    'lpp_en' => 'images/katalogs/Vaks2.jpg',
                    'lpp_ru' => 'images/katalogs/Vaks2.jpg',
                    'btnlabel_lv' => 'Sazināties',
                    'btnlabel_en' => 'Conntact',
                    'btnlabel_ru' => 'Pišiķe',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ]

            ]);

        } else { echo "\e[31mTable is not empty, therefore NOT "; }
    }
}
