<?php

use Illuminate\Database\Seeder;

class katalogs extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('katalogs')->get()->count() == 0){

            DB::table('katalogs')->insert([

                [
                    'galerija_id' => '100',
                    'aktivs' => '1',
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'turn/images/Vaks1.jpg',
                    'lpp_en' => 'turn/images/Vaks1.jpg',
                    'lpp_ru' => 'turn/images/Vaks1.jpg',
                    'btnlabel_lv' => '',
                    'btnlabel_en' => '',
                    'btnlabel_ru' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '100',
                    'aktivs' => '1',
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'turn/images/lpp1.jpg',
                    'lpp_en' => 'turn/images/lpp1.jpg',
                    'lpp_ru' => 'turn/images/lpp1.jpg',
                    'btnlabel_lv' => '',
                    'btnlabel_en' => '',
                    'btnlabel_ru' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '1',
                    'aktivs' => '1',
                    'btn_links' => 'galerijas/IM000082.jpg',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '80',
                    'btn_left' => '57',
                    'lpp_lv' => 'turn/images/lpp2.jpg',
                    'lpp_en' => 'turn/images/lpp2.jpg',
                    'lpp_ru' => 'turn/images/lpp2.jpg',
                    'btnlabel_lv' => 'Apskatīt',
                    'btnlabel_en' => 'Posmotret',
                    'btnlabel_ru' => 'Visit',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '2',
                    'aktivs' => '1',
                    'btn_links' => 'galerijas/IM000083.jpg',
                    'btn_krasa' => 'btn-base-2',
                    'btn_top' => '91',
                    'btn_left' => '30',
                    'lpp_lv' => 'turn/images/lpp3.jpg',
                    'lpp_en' => 'turn/images/lpp3.jpg',
                    'lpp_ru' => 'turn/images/lpp3.jpg',
                    'btnlabel_lv' => 'Galerija',
                    'btnlabel_en' => 'Gallery',
                    'btnlabel_ru' => 'Gaļereja',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '100',
                    'aktivs' => '1',
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'turn/images/lpp4.jpg',
                    'lpp_en' => 'turn/images/lpp4.jpg',
                    'lpp_ru' => 'turn/images/lpp4.jpg',
                    'btnlabel_lv' => 'Galerija',
                    'btnlabel_en' => 'Gallery',
                    'btnlabel_ru' => 'Gaļereja',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '100',
                    'aktivs' => '1',
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'turn/images/lpp5.jpg',
                    'lpp_en' => 'turn/images/lpp5.jpg',
                    'lpp_ru' => 'turn/images/lpp5.jpg',
                    'btnlabel_lv' => '',
                    'btnlabel_en' => '',
                    'btnlabel_ru' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '3',
                    'aktivs' => '1',
                    'btn_links' => 'galerijas/IM000084.jpg',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '80',
                    'btn_left' => '57',
                    'lpp_lv' => 'turn/images/lpp6.jpg',
                    'lpp_en' => 'turn/images/lpp6.jpg',
                    'lpp_ru' => 'turn/images/lpp6.jpg',
                    'btnlabel_lv' => 'Skatīt galeriju',
                    'btnlabel_en' => 'Check',
                    'btnlabel_ru' => 'Posmotrt Gaļereju',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '100',
                    'aktivs' => '1',
                    'btn_links' => '',
                    'btn_krasa' => '',
                    'btn_top' => '',
                    'btn_left' => '',
                    'lpp_lv' => 'turn/images/lpp7.jpg',
                    'lpp_en' => 'turn/images/lpp7.jpg',
                    'lpp_ru' => 'turn/images/lpp7.jpg',
                    'btnlabel_lv' => '',
                    'btnlabel_en' => '',
                    'btnlabel_ru' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '4',
                    'aktivs' => '1',
                    'btn_links' => 'galerijas/IM000084.jpg',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '80',
                    'btn_left' => '57',
                    'lpp_lv' => 'turn/images/lpp8.jpg',
                    'lpp_en' => 'turn/images/lpp8.jpg',
                    'lpp_ru' => 'turn/images/lpp8.jpg',
                    'btnlabel_lv' => 'Apskatīt',
                    'btnlabel_en' => 'Click',
                    'btnlabel_ru' => 'Smotri',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '5',
                    'aktivs' => '1',
                    'btn_links' => 'https://youtu.be/MbQ8wjkkzPw',
                    'btn_krasa' => 'btn-b-base-2',
                    'btn_top' => '90',
                    'btn_left' => '50',
                    'lpp_lv' => 'turn/images/lpp9.jpg',
                    'lpp_en' => 'turn/images/lpp9.jpg',
                    'lpp_ru' => 'turn/images/lpp9.jpg',
                    'btnlabel_lv' => 'Apskatīt video',
                    'btnlabel_en' => 'Video',
                    'btnlabel_ru' => 'Video',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '6',
                    'aktivs' => '1',
                    'btn_links' => 'galerijas/IM000095.jpg',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '90',
                    'btn_left' => '25',
                    'lpp_lv' => 'turn/images/lpp10.jpg',
                    'lpp_en' => 'turn/images/lpp10.jpg',
                    'lpp_ru' => 'turn/images/lpp10.jpg',
                    'btnlabel_lv' => 'Apskatīt',
                    'btnlabel_en' => 'Click',
                    'btnlabel_ru' => 'Smotreķ',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'galerija_id' => '100',
                    'aktivs' => '1',
                    'btn_links' => '#kontakti',
                    'btn_krasa' => 'btn-b-base-1',
                    'btn_top' => '70',
                    'btn_left' => '32',
                    'lpp_lv' => 'turn/images/Vaks2.jpg',
                    'lpp_en' => 'turn/images/Vaks2.jpg',
                    'lpp_ru' => 'turn/images/Vaks2.jpg',
                    'btnlabel_lv' => 'Sazināties',
                    'btnlabel_en' => 'Conntact',
                    'btnlabel_ru' => 'Pišiķe',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ]

            ]);

        } else { echo "\e[31mTable is not empty, therefore NOT "; }
    }
}
